# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/ui_stacksatellite.ui'
#
# Created: Wed Jun 25 13:45:08 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StackSatellite(object):
    def setupUi(self, StackSatellite):
        StackSatellite.setObjectName(_fromUtf8("StackSatellite"))
        StackSatellite.resize(666, 645)
        self.buttonBox = QtGui.QDialogButtonBox(StackSatellite)
        self.buttonBox.setGeometry(QtCore.QRect(240, 600, 171, 27))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.pushButton_inputshapefile = QtGui.QPushButton(StackSatellite)
        self.pushButton_inputshapefile.setGeometry(QtCore.QRect(350, 210, 98, 27))
        self.pushButton_inputshapefile.setObjectName(_fromUtf8("pushButton_inputshapefile"))
        self.groupBox_pixel = QtGui.QGroupBox(StackSatellite)
        self.groupBox_pixel.setGeometry(QtCore.QRect(50, 430, 151, 111))
        self.groupBox_pixel.setObjectName(_fromUtf8("groupBox_pixel"))
        self.checkBox_builtup_index = QtGui.QCheckBox(self.groupBox_pixel)
        self.checkBox_builtup_index.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.checkBox_builtup_index.setObjectName(_fromUtf8("checkBox_builtup_index"))
        self.checkBox_pca_index = QtGui.QCheckBox(self.groupBox_pixel)
        self.checkBox_pca_index.setGeometry(QtCore.QRect(10, 50, 85, 20))
        self.checkBox_pca_index.setObjectName(_fromUtf8("checkBox_pca_index"))
        self.checkBox_pca_classification = QtGui.QCheckBox(self.groupBox_pixel)
        self.checkBox_pca_classification.setGeometry(QtCore.QRect(10, 80, 131, 20))
        self.checkBox_pca_classification.setObjectName(_fromUtf8("checkBox_pca_classification"))
        self.checkBox_reference_diretory = QtGui.QCheckBox(StackSatellite)
        self.checkBox_reference_diretory.setGeometry(QtCore.QRect(40, 350, 141, 20))
        self.checkBox_reference_diretory.setChecked(True)
        self.checkBox_reference_diretory.setObjectName(_fromUtf8("checkBox_reference_diretory"))
        self.groupBox_options = QtGui.QGroupBox(StackSatellite)
        self.groupBox_options.setGeometry(QtCore.QRect(480, 330, 151, 81))
        self.groupBox_options.setObjectName(_fromUtf8("groupBox_options"))
        self.checkBox_restrict_to_city = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_restrict_to_city.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.checkBox_restrict_to_city.setObjectName(_fromUtf8("checkBox_restrict_to_city"))
        self.checkBox_coregistration = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_coregistration.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.checkBox_coregistration.setObjectName(_fromUtf8("checkBox_coregistration"))
        self.pushButton_satellite_folder = QtGui.QPushButton(StackSatellite)
        self.pushButton_satellite_folder.setGeometry(QtCore.QRect(350, 150, 98, 27))
        self.pushButton_satellite_folder.setObjectName(_fromUtf8("pushButton_satellite_folder"))
        self.pushButton_reference_directory = QtGui.QPushButton(StackSatellite)
        self.pushButton_reference_directory.setGeometry(QtCore.QRect(350, 370, 98, 27))
        self.pushButton_reference_directory.setObjectName(_fromUtf8("pushButton_reference_directory"))
        self.lineEdit_reference_directory = QtGui.QLineEdit(StackSatellite)
        self.lineEdit_reference_directory.setEnabled(True)
        self.lineEdit_reference_directory.setGeometry(QtCore.QRect(40, 370, 291, 27))
        self.lineEdit_reference_directory.setObjectName(_fromUtf8("lineEdit_reference_directory"))
        self.label_segmentation = QtGui.QLabel(StackSatellite)
        self.label_segmentation.setGeometry(QtCore.QRect(40, 300, 191, 17))
        self.label_segmentation.setObjectName(_fromUtf8("label_segmentation"))
        self.groupBox_object = QtGui.QGroupBox(StackSatellite)
        self.groupBox_object.setGeometry(QtCore.QRect(400, 430, 181, 81))
        self.groupBox_object.setObjectName(_fromUtf8("groupBox_object"))
        self.checkBox_unsupervised = QtGui.QCheckBox(self.groupBox_object)
        self.checkBox_unsupervised.setGeometry(QtCore.QRect(10, 20, 161, 20))
        self.checkBox_unsupervised.setObjectName(_fromUtf8("checkBox_unsupervised"))
        self.checkBox_supervised = QtGui.QCheckBox(self.groupBox_object)
        self.checkBox_supervised.setGeometry(QtCore.QRect(10, 50, 141, 20))
        self.checkBox_supervised.setObjectName(_fromUtf8("checkBox_supervised"))
        self.label_satellite_folder = QtGui.QLabel(StackSatellite)
        self.label_satellite_folder.setGeometry(QtCore.QRect(40, 132, 191, 17))
        self.label_satellite_folder.setObjectName(_fromUtf8("label_satellite_folder"))
        self.logo_unipv = QtGui.QLabel(StackSatellite)
        self.logo_unipv.setGeometry(QtCore.QRect(460, 10, 91, 81))
        self.logo_unipv.setText(_fromUtf8(""))
        self.logo_unipv.setPixmap(QtGui.QPixmap(_fromUtf8("unipv.png")))
        self.logo_unipv.setObjectName(_fromUtf8("logo_unipv"))
        self.logo_sensum = QtGui.QLabel(StackSatellite)
        self.logo_sensum.setGeometry(QtCore.QRect(120, 20, 241, 61))
        self.logo_sensum.setText(_fromUtf8(""))
        self.logo_sensum.setPixmap(QtGui.QPixmap(_fromUtf8("sensum.png")))
        self.logo_sensum.setObjectName(_fromUtf8("logo_sensum"))
        self.label_title = QtGui.QLabel(StackSatellite)
        self.label_title.setGeometry(QtCore.QRect(220, 100, 201, 21))
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.lineEdit_satellite_folder = QtGui.QLineEdit(StackSatellite)
        self.lineEdit_satellite_folder.setGeometry(QtCore.QRect(40, 150, 291, 27))
        self.lineEdit_satellite_folder.setObjectName(_fromUtf8("lineEdit_satellite_folder"))
        self.comboBox_quantization_mode = QtGui.QComboBox(StackSatellite)
        self.comboBox_quantization_mode.setGeometry(QtCore.QRect(40, 270, 280, 21))
        self.comboBox_quantization_mode.setObjectName(_fromUtf8("comboBox_quantization_mode"))
        self.comboBox_quantization_mode.addItem(_fromUtf8(""))
        self.comboBox_quantization_mode.addItem(_fromUtf8(""))
        self.comboBox_segmentation = QtGui.QComboBox(StackSatellite)
        self.comboBox_segmentation.setGeometry(QtCore.QRect(40, 320, 280, 21))
        self.comboBox_segmentation.setObjectName(_fromUtf8("comboBox_segmentation"))
        self.comboBox_segmentation.addItem(_fromUtf8(""))
        self.comboBox_segmentation.addItem(_fromUtf8(""))
        self.lineEdit_optimazer_polygon = QtGui.QLineEdit(StackSatellite)
        self.lineEdit_optimazer_polygon.setEnabled(False)
        self.lineEdit_optimazer_polygon.setGeometry(QtCore.QRect(360, 548, 191, 27))
        self.lineEdit_optimazer_polygon.setObjectName(_fromUtf8("lineEdit_optimazer_polygon"))
        self.pushButton_optimazer_polygon = QtGui.QPushButton(StackSatellite)
        self.pushButton_optimazer_polygon.setEnabled(False)
        self.pushButton_optimazer_polygon.setGeometry(QtCore.QRect(560, 550, 61, 27))
        self.pushButton_optimazer_polygon.setObjectName(_fromUtf8("pushButton_optimazer_polygon"))
        self.label_input_shapefile = QtGui.QLabel(StackSatellite)
        self.label_input_shapefile.setGeometry(QtCore.QRect(40, 192, 191, 17))
        self.label_input_shapefile.setObjectName(_fromUtf8("label_input_shapefile"))
        self.frame_fundamental = QtGui.QFrame(StackSatellite)
        self.frame_fundamental.setGeometry(QtCore.QRect(480, 150, 151, 151))
        self.frame_fundamental.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_fundamental.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_fundamental.setObjectName(_fromUtf8("frame_fundamental"))
        self.label_nclasses = QtGui.QLabel(self.frame_fundamental)
        self.label_nclasses.setGeometry(QtCore.QRect(11, 101, 112, 16))
        self.label_nclasses.setObjectName(_fromUtf8("label_nclasses"))
        self.spinBox_nclasses = QtGui.QSpinBox(self.frame_fundamental)
        self.spinBox_nclasses.setGeometry(QtCore.QRect(11, 122, 53, 18))
        self.spinBox_nclasses.setObjectName(_fromUtf8("spinBox_nclasses"))
        self.spinBox_niteration = QtGui.QSpinBox(self.frame_fundamental)
        self.spinBox_niteration.setGeometry(QtCore.QRect(11, 77, 53, 18))
        self.spinBox_niteration.setObjectName(_fromUtf8("spinBox_niteration"))
        self.label_niteration = QtGui.QLabel(self.frame_fundamental)
        self.label_niteration.setGeometry(QtCore.QRect(11, 56, 126, 16))
        self.label_niteration.setObjectName(_fromUtf8("label_niteration"))
        self.spinBox_select_criteria = QtGui.QSpinBox(self.frame_fundamental)
        self.spinBox_select_criteria.setGeometry(QtCore.QRect(11, 32, 53, 18))
        self.spinBox_select_criteria.setObjectName(_fromUtf8("spinBox_select_criteria"))
        self.label_select_criteria = QtGui.QLabel(self.frame_fundamental)
        self.label_select_criteria.setGeometry(QtCore.QRect(11, 11, 87, 16))
        self.label_select_criteria.setObjectName(_fromUtf8("label_select_criteria"))
        self.label_optimazer_polygon = QtGui.QLabel(StackSatellite)
        self.label_optimazer_polygon.setGeometry(QtCore.QRect(360, 530, 121, 17))
        self.label_optimazer_polygon.setObjectName(_fromUtf8("label_optimazer_polygon"))
        self.label_quantization_mode = QtGui.QLabel(StackSatellite)
        self.label_quantization_mode.setGeometry(QtCore.QRect(40, 250, 191, 17))
        self.label_quantization_mode.setObjectName(_fromUtf8("label_quantization_mode"))
        self.lineEdit_input_shapefile = QtGui.QLineEdit(StackSatellite)
        self.lineEdit_input_shapefile.setGeometry(QtCore.QRect(40, 210, 291, 27))
        self.lineEdit_input_shapefile.setObjectName(_fromUtf8("lineEdit_input_shapefile"))
        self.logo_eucentre = QtGui.QLabel(StackSatellite)
        self.logo_eucentre.setGeometry(QtCore.QRect(380, 10, 71, 81))
        self.logo_eucentre.setText(_fromUtf8(""))
        self.logo_eucentre.setPixmap(QtGui.QPixmap(_fromUtf8("eucentre.png")))
        self.logo_eucentre.setObjectName(_fromUtf8("logo_eucentre"))
        self.groupBox_texture = QtGui.QGroupBox(StackSatellite)
        self.groupBox_texture.setGeometry(QtCore.QRect(220, 430, 151, 51))
        self.groupBox_texture.setObjectName(_fromUtf8("groupBox_texture"))
        self.checkBox_dissimilarity = QtGui.QCheckBox(self.groupBox_texture)
        self.checkBox_dissimilarity.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.checkBox_dissimilarity.setObjectName(_fromUtf8("checkBox_dissimilarity"))

        self.retranslateUi(StackSatellite)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), StackSatellite.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), StackSatellite.accept)
        QtCore.QMetaObject.connectSlotsByName(StackSatellite)

    def retranslateUi(self, StackSatellite):
        StackSatellite.setWindowTitle(_translate("StackSatellite", "Sensum", None))
        self.pushButton_inputshapefile.setText(_translate("StackSatellite", "...", None))
        self.groupBox_pixel.setTitle(_translate("StackSatellite", "Pixel Based Method", None))
        self.checkBox_builtup_index.setText(_translate("StackSatellite", "Buit-up Index", None))
        self.checkBox_pca_index.setText(_translate("StackSatellite", "PCA Index", None))
        self.checkBox_pca_classification.setText(_translate("StackSatellite", "PCA classification", None))
        self.checkBox_reference_diretory.setText(_translate("StackSatellite", "Reference Directory", None))
        self.groupBox_options.setTitle(_translate("StackSatellite", "Options", None))
        self.checkBox_restrict_to_city.setText(_translate("StackSatellite", "Restrict to City", None))
        self.checkBox_coregistration.setText(_translate("StackSatellite", "Coregistration", None))
        self.pushButton_satellite_folder.setText(_translate("StackSatellite", "...", None))
        self.pushButton_reference_directory.setText(_translate("StackSatellite", "...", None))
        self.label_segmentation.setText(_translate("StackSatellite", "Segmentation", None))
        self.groupBox_object.setTitle(_translate("StackSatellite", "Object Based Method", None))
        self.checkBox_unsupervised.setText(_translate("StackSatellite", "Unsupervised Polygon", None))
        self.checkBox_supervised.setText(_translate("StackSatellite", "Supervised Polygon", None))
        self.label_satellite_folder.setText(_translate("StackSatellite", "Satellite Folder", None))
        self.label_title.setText(_translate("StackSatellite", "<html><head/><body><p><span style=\" font-size:16pt;\">STACK SATELLITE</span></p></body></html>", None))
        self.comboBox_quantization_mode.setItemText(0, _translate("StackSatellite", "Kmeans", None))
        self.comboBox_quantization_mode.setItemText(1, _translate("StackSatellite", "Linear", None))
        self.comboBox_segmentation.setItemText(0, _translate("StackSatellite", "Edison", None))
        self.comboBox_segmentation.setItemText(1, _translate("StackSatellite", "Meanshift", None))
        self.pushButton_optimazer_polygon.setText(_translate("StackSatellite", "...", None))
        self.label_input_shapefile.setText(_translate("StackSatellite", "Input Shapefile", None))
        self.label_nclasses.setText(_translate("StackSatellite", "Number of classes", None))
        self.label_niteration.setText(_translate("StackSatellite", "Number of Iterations", None))
        self.label_select_criteria.setText(_translate("StackSatellite", "Select Criteria", None))
        self.label_optimazer_polygon.setText(_translate("StackSatellite", "Optimazer Polygon", None))
        self.label_quantization_mode.setText(_translate("StackSatellite", "Quantization Mode", None))
        self.groupBox_texture.setTitle(_translate("StackSatellite", "Texture Based Method", None))
        self.checkBox_dissimilarity.setText(_translate("StackSatellite", "Dissimilarity", None))

