# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/ui_segmentation.ui'
#
# Created: Wed Jun 11 12:14:53 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Segmentation(object):
    def setupUi(self, Segmentation):
        Segmentation.setObjectName(_fromUtf8("Segmentation"))
        Segmentation.resize(450, 465)
        Segmentation.setMinimumSize(QtCore.QSize(450, 465))
        Segmentation.setMaximumSize(QtCore.QSize(450, 465))
        self.buttonBox = QtGui.QDialogButtonBox(Segmentation)
        self.buttonBox.setGeometry(QtCore.QRect(120, 420, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.lineEdit_input = QtGui.QLineEdit(Segmentation)
        self.lineEdit_input.setGeometry(QtCore.QRect(20, 60, 291, 27))
        self.lineEdit_input.setObjectName(_fromUtf8("lineEdit_input"))
        self.label_input_file = QtGui.QLabel(Segmentation)
        self.label_input_file.setGeometry(QtCore.QRect(20, 40, 67, 17))
        self.label_input_file.setObjectName(_fromUtf8("label_input_file"))
        self.pushButton_input = QtGui.QPushButton(Segmentation)
        self.pushButton_input.setGeometry(QtCore.QRect(330, 60, 98, 27))
        self.pushButton_input.setObjectName(_fromUtf8("pushButton_input"))
        self.comboBox_method = QtGui.QComboBox(Segmentation)
        self.comboBox_method.setGeometry(QtCore.QRect(21, 170, 231, 27))
        self.comboBox_method.setObjectName(_fromUtf8("comboBox_method"))
        self.comboBox_method.addItem(_fromUtf8(""))
        self.comboBox_method.addItem(_fromUtf8(""))
        self.comboBox_method.addItem(_fromUtf8(""))
        self.comboBox_method.addItem(_fromUtf8(""))
        self.comboBox_method.addItem(_fromUtf8(""))
        self.comboBox_method.addItem(_fromUtf8(""))
        self.comboBox_method.addItem(_fromUtf8(""))
        self.label_output = QtGui.QLabel(Segmentation)
        self.label_output.setGeometry(QtCore.QRect(20, 95, 151, 17))
        self.label_output.setObjectName(_fromUtf8("label_output"))
        self.pushButton_output = QtGui.QPushButton(Segmentation)
        self.pushButton_output.setGeometry(QtCore.QRect(330, 113, 98, 27))
        self.pushButton_output.setObjectName(_fromUtf8("pushButton_output"))
        self.lineEdit_output = QtGui.QLineEdit(Segmentation)
        self.lineEdit_output.setGeometry(QtCore.QRect(20, 113, 291, 27))
        self.lineEdit_output.setObjectName(_fromUtf8("lineEdit_output"))
        self.label_method = QtGui.QLabel(Segmentation)
        self.label_method.setGeometry(QtCore.QRect(20, 150, 151, 17))
        self.label_method.setObjectName(_fromUtf8("label_method"))
        self.label_title = QtGui.QLabel(Segmentation)
        self.label_title.setGeometry(QtCore.QRect(140, 20, 171, 21))
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.groupBox_optimizer = QtGui.QGroupBox(Segmentation)
        self.groupBox_optimizer.setGeometry(QtCore.QRect(30, 210, 381, 112))
        self.groupBox_optimizer.setObjectName(_fromUtf8("groupBox_optimizer"))
        self.lineEdit_optimizer_input = QtGui.QLineEdit(self.groupBox_optimizer)
        self.lineEdit_optimizer_input.setGeometry(QtCore.QRect(12, 30, 271, 21))
        self.lineEdit_optimizer_input.setObjectName(_fromUtf8("lineEdit_optimizer_input"))
        self.pushButton_optimizer_input = QtGui.QPushButton(self.groupBox_optimizer)
        self.pushButton_optimizer_input.setGeometry(QtCore.QRect(290, 20, 77, 27))
        self.pushButton_optimizer_input.setObjectName(_fromUtf8("pushButton_optimizer_input"))
        self.label_nloops = QtGui.QLabel(self.groupBox_optimizer)
        self.label_nloops.setGeometry(QtCore.QRect(30, 59, 42, 16))
        self.label_nloops.setObjectName(_fromUtf8("label_nloops"))
        self.label_criteria = QtGui.QLabel(self.groupBox_optimizer)
        self.label_criteria.setGeometry(QtCore.QRect(100, 59, 45, 16))
        self.label_criteria.setObjectName(_fromUtf8("label_criteria"))
        self.spinBox_nloops = QtGui.QSpinBox(self.groupBox_optimizer)
        self.spinBox_nloops.setGeometry(QtCore.QRect(30, 80, 41, 21))
        self.spinBox_nloops.setObjectName(_fromUtf8("spinBox_nloops"))
        self.spinBox_criteria = QtGui.QSpinBox(self.groupBox_optimizer)
        self.spinBox_criteria.setGeometry(QtCore.QRect(100, 80, 41, 21))
        self.spinBox_criteria.setProperty("value", 4)
        self.spinBox_criteria.setObjectName(_fromUtf8("spinBox_criteria"))
        self.radioButton_floaters = QtGui.QRadioButton(self.groupBox_optimizer)
        self.radioButton_floaters.setGeometry(QtCore.QRect(180, 70, 71, 20))
        self.radioButton_floaters.setChecked(True)
        self.radioButton_floaters.setObjectName(_fromUtf8("radioButton_floaters"))
        self.radioButton_integers = QtGui.QRadioButton(self.groupBox_optimizer)
        self.radioButton_integers.setGeometry(QtCore.QRect(270, 70, 71, 20))
        self.radioButton_integers.setChecked(False)
        self.radioButton_integers.setObjectName(_fromUtf8("radioButton_integers"))
        self.groupBox_options = QtGui.QGroupBox(Segmentation)
        self.groupBox_options.setGeometry(QtCore.QRect(30, 210, 381, 201))
        self.groupBox_options.setObjectName(_fromUtf8("groupBox_options"))
        self.frame_edison = QtGui.QFrame(self.groupBox_options)
        self.frame_edison.setGeometry(QtCore.QRect(50, 60, 301, 91))
        self.frame_edison.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_edison.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_edison.setObjectName(_fromUtf8("frame_edison"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_edison)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_edison_title = QtGui.QLabel(self.frame_edison)
        self.label_edison_title.setObjectName(_fromUtf8("label_edison_title"))
        self.gridLayout_2.addWidget(self.label_edison_title, 0, 1, 1, 1)
        self.label_edison_radius = QtGui.QLabel(self.frame_edison)
        self.label_edison_radius.setObjectName(_fromUtf8("label_edison_radius"))
        self.gridLayout_2.addWidget(self.label_edison_radius, 1, 0, 1, 1)
        self.label_edison_scale = QtGui.QLabel(self.frame_edison)
        self.label_edison_scale.setObjectName(_fromUtf8("label_edison_scale"))
        self.gridLayout_2.addWidget(self.label_edison_scale, 2, 3, 1, 1)
        self.lineEdit_edison_range = QtGui.QLineEdit(self.frame_edison)
        self.lineEdit_edison_range.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_edison_range.setObjectName(_fromUtf8("lineEdit_edison_range"))
        self.gridLayout_2.addWidget(self.lineEdit_edison_range, 1, 4, 1, 1)
        self.lineEdit_edison_scale = QtGui.QLineEdit(self.frame_edison)
        self.lineEdit_edison_scale.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_edison_scale.setObjectName(_fromUtf8("lineEdit_edison_scale"))
        self.gridLayout_2.addWidget(self.lineEdit_edison_scale, 2, 4, 1, 1)
        self.label_edison_range = QtGui.QLabel(self.frame_edison)
        self.label_edison_range.setObjectName(_fromUtf8("label_edison_range"))
        self.gridLayout_2.addWidget(self.label_edison_range, 1, 3, 1, 1)
        self.label_edison_size = QtGui.QLabel(self.frame_edison)
        self.label_edison_size.setObjectName(_fromUtf8("label_edison_size"))
        self.gridLayout_2.addWidget(self.label_edison_size, 2, 0, 1, 1)
        self.lineEdit_edison_size = QtGui.QLineEdit(self.frame_edison)
        self.lineEdit_edison_size.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_edison_size.setObjectName(_fromUtf8("lineEdit_edison_size"))
        self.gridLayout_2.addWidget(self.lineEdit_edison_size, 2, 1, 1, 1)
        self.lineEdit_edison_radius = QtGui.QLineEdit(self.frame_edison)
        self.lineEdit_edison_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_edison_radius.setObjectName(_fromUtf8("lineEdit_edison_radius"))
        self.gridLayout_2.addWidget(self.lineEdit_edison_radius, 1, 1, 1, 1)
        self.frame_region = QtGui.QFrame(self.groupBox_options)
        self.frame_region.setGeometry(QtCore.QRect(50, 50, 301, 101))
        self.frame_region.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_region.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_region.setObjectName(_fromUtf8("frame_region"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_region)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lineEdit_region_color = QtGui.QLineEdit(self.frame_region)
        self.lineEdit_region_color.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_region_color.setObjectName(_fromUtf8("lineEdit_region_color"))
        self.gridLayout_7.addWidget(self.lineEdit_region_color, 3, 1, 1, 1)
        self.lineEdit_region_compactness = QtGui.QLineEdit(self.frame_region)
        self.lineEdit_region_compactness.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_region_compactness.setObjectName(_fromUtf8("lineEdit_region_compactness"))
        self.gridLayout_7.addWidget(self.lineEdit_region_compactness, 2, 4, 1, 1)
        self.label_region_scale = QtGui.QLabel(self.frame_region)
        self.label_region_scale.setObjectName(_fromUtf8("label_region_scale"))
        self.gridLayout_7.addWidget(self.label_region_scale, 3, 3, 1, 1)
        self.label_region_color = QtGui.QLabel(self.frame_region)
        self.label_region_color.setObjectName(_fromUtf8("label_region_color"))
        self.gridLayout_7.addWidget(self.label_region_color, 3, 0, 1, 1)
        self.label_region_euclidean = QtGui.QLabel(self.frame_region)
        self.label_region_euclidean.setObjectName(_fromUtf8("label_region_euclidean"))
        self.gridLayout_7.addWidget(self.label_region_euclidean, 2, 0, 1, 1)
        self.label_region_compactness = QtGui.QLabel(self.frame_region)
        self.label_region_compactness.setObjectName(_fromUtf8("label_region_compactness"))
        self.gridLayout_7.addWidget(self.label_region_compactness, 2, 3, 1, 1)
        self.lineEdit_region_scale = QtGui.QLineEdit(self.frame_region)
        self.lineEdit_region_scale.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_region_scale.setObjectName(_fromUtf8("lineEdit_region_scale"))
        self.gridLayout_7.addWidget(self.lineEdit_region_scale, 3, 4, 1, 1)
        self.lineEdit_region_euclidean = QtGui.QLineEdit(self.frame_region)
        self.lineEdit_region_euclidean.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_region_euclidean.setObjectName(_fromUtf8("lineEdit_region_euclidean"))
        self.gridLayout_7.addWidget(self.lineEdit_region_euclidean, 2, 1, 1, 1)
        self.label_region = QtGui.QLabel(self.frame_region)
        self.label_region.setObjectName(_fromUtf8("label_region"))
        self.gridLayout_7.addWidget(self.label_region, 0, 1, 1, 1)
        self.frame_baatz = QtGui.QFrame(self.groupBox_options)
        self.frame_baatz.setGeometry(QtCore.QRect(50, 50, 301, 91))
        self.frame_baatz.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_baatz.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_baatz.setObjectName(_fromUtf8("frame_baatz"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_baatz)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit_baatz_color = QtGui.QLineEdit(self.frame_baatz)
        self.lineEdit_baatz_color.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_baatz_color.setObjectName(_fromUtf8("lineEdit_baatz_color"))
        self.gridLayout_3.addWidget(self.lineEdit_baatz_color, 3, 1, 1, 1)
        self.lineEdit_baatz_euclidean = QtGui.QLineEdit(self.frame_baatz)
        self.lineEdit_baatz_euclidean.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_baatz_euclidean.setObjectName(_fromUtf8("lineEdit_baatz_euclidean"))
        self.gridLayout_3.addWidget(self.lineEdit_baatz_euclidean, 2, 1, 1, 1)
        self.label_baatz_euclidean = QtGui.QLabel(self.frame_baatz)
        self.label_baatz_euclidean.setObjectName(_fromUtf8("label_baatz_euclidean"))
        self.gridLayout_3.addWidget(self.label_baatz_euclidean, 2, 0, 1, 1)
        self.label_baatz_compactness = QtGui.QLabel(self.frame_baatz)
        self.label_baatz_compactness.setObjectName(_fromUtf8("label_baatz_compactness"))
        self.gridLayout_3.addWidget(self.label_baatz_compactness, 2, 3, 1, 1)
        self.lineEdit_baatz_compactness = QtGui.QLineEdit(self.frame_baatz)
        self.lineEdit_baatz_compactness.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_baatz_compactness.setObjectName(_fromUtf8("lineEdit_baatz_compactness"))
        self.gridLayout_3.addWidget(self.lineEdit_baatz_compactness, 2, 4, 1, 1)
        self.lineEdit_baatz_scale = QtGui.QLineEdit(self.frame_baatz)
        self.lineEdit_baatz_scale.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_baatz_scale.setObjectName(_fromUtf8("lineEdit_baatz_scale"))
        self.gridLayout_3.addWidget(self.lineEdit_baatz_scale, 3, 4, 1, 1)
        self.label_baatz_scale = QtGui.QLabel(self.frame_baatz)
        self.label_baatz_scale.setObjectName(_fromUtf8("label_baatz_scale"))
        self.gridLayout_3.addWidget(self.label_baatz_scale, 3, 3, 1, 1)
        self.label_baatz_color = QtGui.QLabel(self.frame_baatz)
        self.label_baatz_color.setObjectName(_fromUtf8("label_baatz_color"))
        self.gridLayout_3.addWidget(self.label_baatz_color, 3, 0, 1, 1)
        self.label_baatz = QtGui.QLabel(self.frame_baatz)
        self.label_baatz.setObjectName(_fromUtf8("label_baatz"))
        self.gridLayout_3.addWidget(self.label_baatz, 1, 1, 1, 1)
        self.frame_morphological = QtGui.QFrame(self.groupBox_options)
        self.frame_morphological.setGeometry(QtCore.QRect(50, 60, 301, 91))
        self.frame_morphological.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_morphological.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_morphological.setObjectName(_fromUtf8("frame_morphological"))
        self.gridLayout = QtGui.QGridLayout(self.frame_morphological)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_morphological_start = QtGui.QLineEdit(self.frame_morphological)
        self.lineEdit_morphological_start.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_morphological_start.setObjectName(_fromUtf8("lineEdit_morphological_start"))
        self.gridLayout.addWidget(self.lineEdit_morphological_start, 3, 1, 1, 1)
        self.lineEdit_morphological_radius = QtGui.QLineEdit(self.frame_morphological)
        self.lineEdit_morphological_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_morphological_radius.setObjectName(_fromUtf8("lineEdit_morphological_radius"))
        self.gridLayout.addWidget(self.lineEdit_morphological_radius, 2, 1, 1, 1)
        self.label_morphological_size = QtGui.QLabel(self.frame_morphological)
        self.label_morphological_size.setObjectName(_fromUtf8("label_morphological_size"))
        self.gridLayout.addWidget(self.label_morphological_size, 2, 0, 1, 1)
        self.label_morphological_sigma = QtGui.QLabel(self.frame_morphological)
        self.label_morphological_sigma.setObjectName(_fromUtf8("label_morphological_sigma"))
        self.gridLayout.addWidget(self.label_morphological_sigma, 2, 3, 1, 1)
        self.lineEdit_morphological_sigma = QtGui.QLineEdit(self.frame_morphological)
        self.lineEdit_morphological_sigma.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_morphological_sigma.setObjectName(_fromUtf8("lineEdit_morphological_sigma"))
        self.gridLayout.addWidget(self.lineEdit_morphological_sigma, 2, 4, 1, 1)
        self.lineEdit_morphological_step = QtGui.QLineEdit(self.frame_morphological)
        self.lineEdit_morphological_step.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_morphological_step.setObjectName(_fromUtf8("lineEdit_morphological_step"))
        self.gridLayout.addWidget(self.lineEdit_morphological_step, 3, 4, 1, 1)
        self.label_morphological_step = QtGui.QLabel(self.frame_morphological)
        self.label_morphological_step.setObjectName(_fromUtf8("label_morphological_step"))
        self.gridLayout.addWidget(self.label_morphological_step, 3, 3, 1, 1)
        self.label_morphological_start = QtGui.QLabel(self.frame_morphological)
        self.label_morphological_start.setObjectName(_fromUtf8("label_morphological_start"))
        self.gridLayout.addWidget(self.label_morphological_start, 3, 0, 1, 1)
        self.label_morphological_title = QtGui.QLabel(self.frame_morphological)
        self.label_morphological_title.setObjectName(_fromUtf8("label_morphological_title"))
        self.gridLayout.addWidget(self.label_morphological_title, 1, 1, 1, 1)
        self.frame_watershed = QtGui.QFrame(self.groupBox_options)
        self.frame_watershed.setGeometry(QtCore.QRect(50, 60, 301, 61))
        self.frame_watershed.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_watershed.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_watershed.setObjectName(_fromUtf8("frame_watershed"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_watershed)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lineEdit_watershed_level = QtGui.QLineEdit(self.frame_watershed)
        self.lineEdit_watershed_level.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_watershed_level.setObjectName(_fromUtf8("lineEdit_watershed_level"))
        self.gridLayout_6.addWidget(self.lineEdit_watershed_level, 2, 4, 1, 1)
        self.lineEdit_watershed_threshold = QtGui.QLineEdit(self.frame_watershed)
        self.lineEdit_watershed_threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_watershed_threshold.setObjectName(_fromUtf8("lineEdit_watershed_threshold"))
        self.gridLayout_6.addWidget(self.lineEdit_watershed_threshold, 2, 1, 1, 1)
        self.label_watershed = QtGui.QLabel(self.frame_watershed)
        self.label_watershed.setObjectName(_fromUtf8("label_watershed"))
        self.gridLayout_6.addWidget(self.label_watershed, 1, 1, 1, 1)
        self.label_watershed_threshold = QtGui.QLabel(self.frame_watershed)
        self.label_watershed_threshold.setObjectName(_fromUtf8("label_watershed_threshold"))
        self.gridLayout_6.addWidget(self.label_watershed_threshold, 2, 0, 1, 1)
        self.label_watershed_level = QtGui.QLabel(self.frame_watershed)
        self.label_watershed_level.setObjectName(_fromUtf8("label_watershed_level"))
        self.gridLayout_6.addWidget(self.label_watershed_level, 2, 3, 1, 1)
        self.frame_meanshift = QtGui.QFrame(self.groupBox_options)
        self.frame_meanshift.setGeometry(QtCore.QRect(50, 30, 301, 141))
        self.frame_meanshift.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_meanshift.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_meanshift.setObjectName(_fromUtf8("frame_meanshift"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_meanshift)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lineEdit_meanshift_radius = QtGui.QLineEdit(self.frame_meanshift)
        self.lineEdit_meanshift_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_meanshift_radius.setObjectName(_fromUtf8("lineEdit_meanshift_radius"))
        self.gridLayout_4.addWidget(self.lineEdit_meanshift_radius, 2, 1, 1, 1)
        self.lineEdit_meanshift_iterations = QtGui.QLineEdit(self.frame_meanshift)
        self.lineEdit_meanshift_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_meanshift_iterations.setObjectName(_fromUtf8("lineEdit_meanshift_iterations"))
        self.gridLayout_4.addWidget(self.lineEdit_meanshift_iterations, 3, 4, 1, 1)
        self.label_meanshift_minsize = QtGui.QLabel(self.frame_meanshift)
        self.label_meanshift_minsize.setObjectName(_fromUtf8("label_meanshift_minsize"))
        self.gridLayout_4.addWidget(self.label_meanshift_minsize, 4, 0, 1, 1)
        self.label_meanshift_spatial = QtGui.QLabel(self.frame_meanshift)
        self.label_meanshift_spatial.setObjectName(_fromUtf8("label_meanshift_spatial"))
        self.gridLayout_4.addWidget(self.label_meanshift_spatial, 2, 0, 1, 1)
        self.lineEdit_meanshift_range = QtGui.QLineEdit(self.frame_meanshift)
        self.lineEdit_meanshift_range.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_meanshift_range.setObjectName(_fromUtf8("lineEdit_meanshift_range"))
        self.gridLayout_4.addWidget(self.lineEdit_meanshift_range, 2, 4, 1, 1)
        self.lineEdit_meanshift_threshold = QtGui.QLineEdit(self.frame_meanshift)
        self.lineEdit_meanshift_threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_meanshift_threshold.setObjectName(_fromUtf8("lineEdit_meanshift_threshold"))
        self.gridLayout_4.addWidget(self.lineEdit_meanshift_threshold, 3, 1, 1, 1)
        self.label_meanshift_iterations = QtGui.QLabel(self.frame_meanshift)
        self.label_meanshift_iterations.setObjectName(_fromUtf8("label_meanshift_iterations"))
        self.gridLayout_4.addWidget(self.label_meanshift_iterations, 3, 3, 1, 1)
        self.label_meanshift_range = QtGui.QLabel(self.frame_meanshift)
        self.label_meanshift_range.setObjectName(_fromUtf8("label_meanshift_range"))
        self.gridLayout_4.addWidget(self.label_meanshift_range, 2, 3, 1, 1)
        self.lineEdit_meanshift_minsize = QtGui.QLineEdit(self.frame_meanshift)
        self.lineEdit_meanshift_minsize.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_meanshift_minsize.setObjectName(_fromUtf8("lineEdit_meanshift_minsize"))
        self.gridLayout_4.addWidget(self.lineEdit_meanshift_minsize, 4, 1, 1, 1)
        self.label_meanshift_threshold = QtGui.QLabel(self.frame_meanshift)
        self.label_meanshift_threshold.setObjectName(_fromUtf8("label_meanshift_threshold"))
        self.gridLayout_4.addWidget(self.label_meanshift_threshold, 3, 0, 1, 1)
        self.label_meanshift = QtGui.QLabel(self.frame_meanshift)
        self.label_meanshift.setObjectName(_fromUtf8("label_meanshift"))
        self.gridLayout_4.addWidget(self.label_meanshift, 1, 1, 1, 1)
        self.frame_felzenszwalb = QtGui.QFrame(self.groupBox_options)
        self.frame_felzenszwalb.setGeometry(QtCore.QRect(50, 60, 301, 93))
        self.frame_felzenszwalb.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_felzenszwalb.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_felzenszwalb.setObjectName(_fromUtf8("frame_felzenszwalb"))
        self.label_felzenszwalb = QtGui.QLabel(self.frame_felzenszwalb)
        self.label_felzenszwalb.setGeometry(QtCore.QRect(100, 10, 79, 16))
        self.label_felzenszwalb.setObjectName(_fromUtf8("label_felzenszwalb"))
        self.layoutWidget = QtGui.QWidget(self.frame_felzenszwalb)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 32, 279, 50))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_felzenszwalb_scale = QtGui.QLabel(self.layoutWidget)
        self.label_felzenszwalb_scale.setObjectName(_fromUtf8("label_felzenszwalb_scale"))
        self.gridLayout_8.addWidget(self.label_felzenszwalb_scale, 0, 0, 1, 1)
        self.lineEdit_felzenszwalb_scale = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_felzenszwalb_scale.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_felzenszwalb_scale.setObjectName(_fromUtf8("lineEdit_felzenszwalb_scale"))
        self.gridLayout_8.addWidget(self.lineEdit_felzenszwalb_scale, 0, 1, 1, 1)
        self.label_felzenszwalb_sigma = QtGui.QLabel(self.layoutWidget)
        self.label_felzenszwalb_sigma.setObjectName(_fromUtf8("label_felzenszwalb_sigma"))
        self.gridLayout_8.addWidget(self.label_felzenszwalb_sigma, 0, 2, 1, 1)
        self.lineEdit_felzenszwalb_sigma = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_felzenszwalb_sigma.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_felzenszwalb_sigma.setObjectName(_fromUtf8("lineEdit_felzenszwalb_sigma"))
        self.gridLayout_8.addWidget(self.lineEdit_felzenszwalb_sigma, 0, 3, 1, 1)
        self.label_felzenszwalb_minsize = QtGui.QLabel(self.layoutWidget)
        self.label_felzenszwalb_minsize.setObjectName(_fromUtf8("label_felzenszwalb_minsize"))
        self.gridLayout_8.addWidget(self.label_felzenszwalb_minsize, 1, 1, 1, 1)
        self.lineEdit_felzenszwalb_minsize = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_felzenszwalb_minsize.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_felzenszwalb_minsize.setObjectName(_fromUtf8("lineEdit_felzenszwalb_minsize"))
        self.gridLayout_8.addWidget(self.lineEdit_felzenszwalb_minsize, 1, 2, 1, 1)
        self.checkBox_optimizer = QtGui.QCheckBox(Segmentation)
        self.checkBox_optimizer.setGeometry(QtCore.QRect(280, 170, 85, 20))
        self.checkBox_optimizer.setObjectName(_fromUtf8("checkBox_optimizer"))

        self.retranslateUi(Segmentation)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Segmentation.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Segmentation.reject)
        QtCore.QMetaObject.connectSlotsByName(Segmentation)

    def retranslateUi(self, Segmentation):
        Segmentation.setWindowTitle(_translate("Segmentation", "SensumTools", None))
        self.label_input_file.setText(_translate("Segmentation", "Input file:", None))
        self.pushButton_input.setText(_translate("Segmentation", "...", None))
        self.comboBox_method.setItemText(0, _translate("Segmentation", "Felzenszwalb", None))
        self.comboBox_method.setItemText(1, _translate("Segmentation", "Watershed", None))
        self.comboBox_method.setItemText(2, _translate("Segmentation", "Edison", None))
        self.comboBox_method.setItemText(3, _translate("Segmentation", "Baatz", None))
        self.comboBox_method.setItemText(4, _translate("Segmentation", "Meanshift", None))
        self.comboBox_method.setItemText(5, _translate("Segmentation", "Morphological Profiles", None))
        self.comboBox_method.setItemText(6, _translate("Segmentation", "Region Growing", None))
        self.label_output.setText(_translate("Segmentation", "Output ESRI Shapefile:", None))
        self.pushButton_output.setText(_translate("Segmentation", "...", None))
        self.label_method.setText(_translate("Segmentation", "Segmentation methodology:", None))
        self.label_title.setText(_translate("Segmentation", "<html><head/><body><p><span style=\" font-size:16pt;\">SEGMENTATION</span></p></body></html>", None))
        self.groupBox_optimizer.setTitle(_translate("Segmentation", "Optimizer", None))
        self.pushButton_optimizer_input.setText(_translate("Segmentation", "...", None))
        self.label_nloops.setText(_translate("Segmentation", "N Loop", None))
        self.label_criteria.setText(_translate("Segmentation", "Criteria", None))
        self.radioButton_floaters.setText(_translate("Segmentation", "Floaters", None))
        self.radioButton_integers.setText(_translate("Segmentation", "Integers", None))
        self.groupBox_options.setTitle(_translate("Segmentation", "Options", None))
        self.label_edison_title.setText(_translate("Segmentation", "Edison", None))
        self.label_edison_radius.setText(_translate("Segmentation", "Spatial radius ", None))
        self.label_edison_scale.setText(_translate("Segmentation", "Scale", None))
        self.lineEdit_edison_range.setText(_translate("Segmentation", "0", None))
        self.lineEdit_edison_scale.setText(_translate("Segmentation", "0", None))
        self.label_edison_range.setText(_translate("Segmentation", "Range Radius", None))
        self.label_edison_size.setText(_translate("Segmentation", "Minimum size", None))
        self.lineEdit_edison_size.setText(_translate("Segmentation", "0", None))
        self.lineEdit_edison_radius.setText(_translate("Segmentation", "0", None))
        self.lineEdit_region_color.setText(_translate("Segmentation", "0", None))
        self.lineEdit_region_compactness.setText(_translate("Segmentation", "0", None))
        self.label_region_scale.setText(_translate("Segmentation", "Scale", None))
        self.label_region_color.setText(_translate("Segmentation", "Baatz Color", None))
        self.label_region_euclidean.setText(_translate("Segmentation", "Euclidean threshold", None))
        self.label_region_compactness.setText(_translate("Segmentation", "Compactness", None))
        self.lineEdit_region_scale.setText(_translate("Segmentation", "0", None))
        self.lineEdit_region_euclidean.setText(_translate("Segmentation", "0", None))
        self.label_region.setText(_translate("Segmentation", "Region Growing", None))
        self.lineEdit_baatz_color.setText(_translate("Segmentation", "0", None))
        self.lineEdit_baatz_euclidean.setText(_translate("Segmentation", "0", None))
        self.label_baatz_euclidean.setText(_translate("Segmentation", "Euclidean thr.", None))
        self.label_baatz_compactness.setText(_translate("Segmentation", "Compactness", None))
        self.lineEdit_baatz_compactness.setText(_translate("Segmentation", "0", None))
        self.lineEdit_baatz_scale.setText(_translate("Segmentation", "0", None))
        self.label_baatz_scale.setText(_translate("Segmentation", "Scale", None))
        self.label_baatz_color.setText(_translate("Segmentation", "Baatz color", None))
        self.label_baatz.setText(_translate("Segmentation", "Baatz", None))
        self.lineEdit_morphological_start.setText(_translate("Segmentation", "0", None))
        self.lineEdit_morphological_radius.setText(_translate("Segmentation", "0", None))
        self.label_morphological_size.setText(_translate("Segmentation", "Size", None))
        self.label_morphological_sigma.setText(_translate("Segmentation", "Sigma", None))
        self.lineEdit_morphological_sigma.setText(_translate("Segmentation", "0", None))
        self.lineEdit_morphological_step.setText(_translate("Segmentation", "0", None))
        self.label_morphological_step.setText(_translate("Segmentation", "Step", None))
        self.label_morphological_start.setText(_translate("Segmentation", "Start", None))
        self.label_morphological_title.setText(_translate("Segmentation", "Morphological", None))
        self.lineEdit_watershed_level.setText(_translate("Segmentation", "0", None))
        self.lineEdit_watershed_threshold.setText(_translate("Segmentation", "0", None))
        self.label_watershed.setText(_translate("Segmentation", "Watershed", None))
        self.label_watershed_threshold.setText(_translate("Segmentation", "Threshold", None))
        self.label_watershed_level.setText(_translate("Segmentation", "Level", None))
        self.lineEdit_meanshift_radius.setText(_translate("Segmentation", "0", None))
        self.lineEdit_meanshift_iterations.setText(_translate("Segmentation", "0", None))
        self.label_meanshift_minsize.setText(_translate("Segmentation", "Minimum size", None))
        self.label_meanshift_spatial.setText(_translate("Segmentation", "Spatial radius", None))
        self.lineEdit_meanshift_range.setText(_translate("Segmentation", "0", None))
        self.lineEdit_meanshift_threshold.setText(_translate("Segmentation", "0", None))
        self.label_meanshift_iterations.setText(_translate("Segmentation", "Max Iterations", None))
        self.label_meanshift_range.setText(_translate("Segmentation", "Range", None))
        self.lineEdit_meanshift_minsize.setText(_translate("Segmentation", "0", None))
        self.label_meanshift_threshold.setText(_translate("Segmentation", "Threshold", None))
        self.label_meanshift.setText(_translate("Segmentation", "Meanshift", None))
        self.label_felzenszwalb.setText(_translate("Segmentation", "Felzenszwalb", None))
        self.label_felzenszwalb_scale.setText(_translate("Segmentation", "Scale", None))
        self.lineEdit_felzenszwalb_scale.setText(_translate("Segmentation", "0", None))
        self.label_felzenszwalb_sigma.setText(_translate("Segmentation", "Sigma", None))
        self.lineEdit_felzenszwalb_sigma.setText(_translate("Segmentation", "0", None))
        self.label_felzenszwalb_minsize.setText(_translate("Segmentation", "Min Size", None))
        self.lineEdit_felzenszwalb_minsize.setText(_translate("Segmentation", "0", None))
        self.checkBox_optimizer.setText(_translate("Segmentation", "Optimizer", None))

